App/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
    path('accounts/',include('accounts.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import Dashboard,Delete_course,Update_Course,Create_Course,Add_Catagorey,List_Catagorey,Delete_catagorey,Update_Catagorey,Update_User,Register,Login,List_contact,Update_contact,delete_contact,List_user,Parvelege,detail_customer,True_customer,False_customer,Logout_user,Par_Create_User,Accessorey,access_user,access_user_False,List_Course,Update_Customer,Update_Website_specifications,Check_Comments

app_name = 'accounts'

urlpatterns = [
    path('Dashboard/',Dashboard,name='dashboard'),
    path('delete_course/<int:id>/',Delete_course,name='delete_course'),
    path('Update_Course/<int:pk>/',Update_Course.as_view(),name='update_course'),
    path('Create_Course/',Create_Course.as_view(),name='create_course'),
    path('Add_catagorey/',Add_Catagorey.as_view(),name='add_catagorey'),
    path('List_catagorey/',List_Catagorey,name='list_catagorey'),
    path('delete_catagorey/<int:id>/',Delete_catagorey,name='delete_catagorey'),
    path('Update_catagorey/<int:pk>/',Update_Catagorey.as_view(),name='update_catagorey'),
    path('Update_user/<int:pk>/',Update_User.as_view(),name='update_user'),
    path('login/',Login,name='login'),
    path('register/',Register,name='register'),
    path('contact_list/',List_contact,name='list_contact'),
    path('update_contact/<int:pk>/',Update_contact.as_view(),name='update_contact'),
    path('delete/<int:id>/',delete_contact,name='delete_contact'),
    path('list_user/',List_user,name='list_user'),
    path('parvalege/<int:id>/',Parvelege,name='parvalege'),
    path('detail_customer_p/<int:id>/',detail_customer,name='detail_customer_p'),
    path('True_Customer/<int:id>/',True_customer,name='true_customer'),
    path('False_Customer/<int:id>/',False_customer,name='false_customer'),
    path('logout_user',Logout_user,name='logout'),
    path('Par_Create_User/',Par_Create_User,name='Par_Create_User'),
    path('Accessorey/',Accessorey,name='access'),
    path('access_users/<int:id>/',access_user,name='access_users'),
    path('access_users_False/<int:id>/',access_user_False,name='access_users_false'),
    path('list_course/',List_Course,name='list_course'),
    path('Update_Customer/<int:pk>/',Update_Customer.as_view(),name='update_customer'),
    path('Update_About_Web/<int:pk>/',Update_Website_specifications.as_view(),name='update_about_web'),
    path('check_comments/',Check_Comments,name='check_comments'),
]

accounts/models.py
from django.db import models

from django_jalali.db import models as jmodels
from django.contrib.auth.models import AbstractUser


# Create your models here.



class User(AbstractUser):
    
    phone = models.CharField(max_length=10)
    address = models.TextField(null=True,blank=True)
    Image  = models.ImageField(upload_to='user/',default='user/1.jpg')
    Techer = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    
    

accounts/views.py
from django.shortcuts import render,HttpResponse,redirect,HttpResponseRedirect
from web.models import Catagory,Course,Customer,Contact,About,Comment
from .models import User
from django.urls import reverse_lazy,reverse
from django.views.generic import UpdateView,CreateView
from django.contrib.auth import login,logout
from accounts.form import LoginForm,register
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from .mixens import FieldsMixin,Website_mixin,Mixin_Customer,Contact_Mixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator

# Create your views here.

def Register(request):
    if request.method == 'POST':
        form = register(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            
            return redirect('accounts:dashboard')
    form = register()
    return render(request,'register/index.html',{'form':form})



def Login(request):
    if request.method == 'POST':
        redirect_to = request.GET.get('next', 'accounts:dashboard')
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return redirect(redirect_to)
        else:
            return HttpResponse('data is Note Valid')
    form = LoginForm()
    return render(request,'login/index.html',{'form':form})



def Logout_user(request):
    logout(request)
    return redirect('web:website')



@login_required(login_url='/accounts/login/')
def Dashboard(request):
    count_users = User.objects.all().count()
    count_course = Course.objects.all().count()
    count_contact = Contact.objects.all().count()
    count_customer = Customer.objects.all().count()
    cont = Contact.objects.filter(active=False).count()
    if request.user.is_authenticated:
        if request.user.is_superuser or request.user.Techer:


            course = Customer.objects.all()
            contax = {
            'course':course,
            'count_users':count_users,
            'count_course':count_course,
            'count_contact':count_contact,
            'count_customer':count_customer
            }
            return render(request,'dashboard/index.html',contax)
    
    course = Customer.objects.filter(user=request.user)
    contax = {
            'course':course,
            'cont':cont
            }
    return render(request,'dashboard/index.html',contax)
    


class Update_User(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'dashboard/Update_user.html'
    fields = ['phone','address','Image','Techer','username']
    def get_form(self, form_class=None):
        form = super(Update_User, self).get_form(form_class)
        form['phone'].field.widget.attrs.update({'class' : 'form-control'})
        form['address'].field.widget.attrs.update({'class' : 'form-control'})
        form['Image'].field.widget.attrs.update({'class' : 'form-control'})
        form['Techer'].field.widget.attrs.update({'class' : 'form-control'})
        form['username'].field.widget.attrs.update({'class' : 'form-control'})
        return form
    success_url = reverse_lazy('accounts:dashboard')
@login_required(login_url='/accounts/login/')    
def Delete_course(request,id):
    delete_course = Course.objects.filter(id=id)
    delete_course.delete()
    return redirect('accounts:dashboard')
def List_Course(request):
    if request.user.is_authenticated:
        if request.user.is_superuser or request.user.Techer:
            course = Course.objects.all()
            contax = {
                'course':course }
            return render(request,'dashboard/list_Course.html',contax)
    
    return HttpResponse('You Dont Access The Page')
class Update_Course(LoginRequiredMixin,FieldsMixin,UpdateView):
    model = Course
    template_name = 'dashboard/Update_course.html'
    fields = '__all__'
    def get_form(self, form_class=None):
        form = super(Update_Course, self).get_form(form_class)
        form['title'].field.widget.attrs.update({'class' : 'form-control'})
        form['video'].field.widget.attrs.update({'class' : 'form-control'})
        form['image'].field.widget.attrs.update({'class' : 'form-control'})
        form['about'].field.widget.attrs.update({'class' : 'form-control','id':'summernote'})
        form['grammer'].field.widget.attrs.update({'class' : 'form-control'})
        form['catagorey'].field.widget.attrs.update({'class' : 'form-control'})
        form['user'].field.widget.attrs.update({'class' : 'form-control'})
       
        
        return form
    success_url = reverse_lazy('accounts:list_course')


class Create_Course(LoginRequiredMixin,FieldsMixin,CreateView):
    model = Course
    template_name = 'dashboard/Update_course.html'
    fields = '__all__'
    def get_form(self, form_class=None):
        form = super(Create_Course, self).get_form(form_class)
        form['title'].field.widget.attrs.update({'class' : 'form-control'})
        form['video'].field.widget.attrs.update({'class' : 'form-control'})
        form['image'].field.widget.attrs.update({'class' : 'form-control'})
        form['about'].field.widget.attrs.update({'class' : 'form-control','id':'summernote'})
        form['grammer'].field.widget.attrs.update({'class' : 'form-control'})
        form['catagorey'].field.widget.attrs.update({'class' : 'form-control'})
        form['user'].field.widget.attrs.update({'class' : 'form-control'})
        return form
    def get_initial(self,*args,**kwargs):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['milad'] = 'Create Course'
        return context
    success_url = reverse_lazy('accounts:dashboard')

class Add_Catagorey(LoginRequiredMixin,CreateView):
    model = Catagory
    template_name = 'dashboard/Add_catagorey.html'
    fields = '__all__'
    def get_form(self, form_class=None):
        form = super(Add_Catagorey, self).get_form(form_class)
        form['name'].field.widget.attrs.update({'class' : 'form-control'})
        form['image'].field.widget.attrs.update({'class' : 'form-control'})
        return form
    success_url = reverse_lazy('accounts:dashboard')

@login_required(login_url='/accounts/login/')
def List_Catagorey(request):
    catagorey = Catagory.objects.all()
    contax = {
        'catagorey':catagorey
    }
    return render(request,'dashboard/List_catagorey.html',contax)
@login_required(login_url='/accounts/login/')
def Delete_catagorey(request,id):
    delete_catagorey = Catagory.objects.filter(id=id)
    delete_catagorey.delete()
    return redirect('accounts:list_catagorey')

class Update_Catagorey(LoginRequiredMixin,UpdateView):
    model = Catagory
    template_name = 'dashboard/Add_catagorey.html'
    fields = '__all__'
    def get_form(self, form_class=None):
        form = super(Update_Catagorey, self).get_form(form_class)
        form['name'].field.widget.attrs.update({'class' : 'form-control'})
        form['image'].field.widget.attrs.update({'class' : 'form-control'})
        return form
    success_url = reverse_lazy('accounts:list_catagorey')

@login_required(login_url='/accounts/login/')
def List_contact(request):
    if request.user.is_superuser or request.user.Techer:

        contact = Contact.objects.all()
        cont = Contact.objects.filter(active=False).count()
        contact_false = Contact.objects.all().update(active=True)
        contax = {
        'contact':contact,
        'cont':cont
        }
        return render(request,'dashboard/contact_list.html',contax)
    else:
        return HttpResponse('You Dont Access The Page')

@login_required(login_url='/accounts/login/')
def delete_contact(request,id):
    delete_c = Contact.objects.get(id=id)
    delete_c.delete()
    return redirect('accounts:list_contact')

class Update_contact(LoginRequiredMixin,Contact_Mixin,UpdateView):
    model = Contact
    template_name = 'dashboard/Update_contact.html'
    fields = '__all__'
    def get_form(self, form_class=None):
        form = super(Update_contact, self).get_form(form_class)
        form['Name'].field.widget.attrs.update({'class' : 'form-control','placeholder':'Your Name'})
        form['Email'].field.widget.attrs.update({'class' : 'form-control','placeholder':'Your E-mail'})
        form['Sunjects'].field.widget.attrs.update({'class' : 'form-control','placeholder':'Your Subjects'})
        form['Message'].field.widget.attrs.update({'class' : 'form-control','placeholder':'Your Message','id':'summernote'})
        form['active'].field.widget.attrs.update({'class' : 'form-control'})
        return form
    success_url = reverse_lazy('accounts:list_contact')


@login_required(login_url='/accounts/login/')
def List_user(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            users = Customer.objects.all()
            queryset = Customer.objects.filter().select_related('user').values('user__username','user__id','user__Image','user__email','user__phone','user__address').distinct()
            
            for item in queryset:
                print(item['user__Image'])
                

        else:
            return HttpResponse('You Dont Acceese The Page')
    contax = {
        'users':users,
        'queryset':queryset
        
    }
    return render(request,'dashboard/parvalege_user.html',contax)
@login_required(login_url='/accounts/login/')
def Parvelege(request,id):
    Users = User.objects.filter(id=id)
    Users.update(Techer=False)
    return redirect('accounts:list_user')
@login_required(login_url='/accounts/login/')
def detail_customer(request,id):
    if request.user.is_authenticated:

accounts/templates/dashboard/Accessorey.html
{% extends 'base_accounts.html' %}
{% load static %}
{% block parvalege %}active{% endblock %}
{% block pre_open %}menu-open{% endblock %}
{% block pre %}active{% endblock %}
{% block pre_all %}active{% endblock %}



{% block main %}
<form action="{% url 'accounts:Par_Create_User' %}" method="POST" enctype="multipart/form-data">
<div class="card">
    <div class="card-header">
      <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped" style="text-align: center;">
        <thead>
        <tr style="background: black;color: white;">
          <th>Date</th>
          <th>User</th>
          <th>Image</th>
          
          <th>Parvalege</th>
          
        </tr>
        </thead>
        <tbody>
      
        {% for j in users %}
        
        <tr>
          
           
          <td>{{j.date}}</td>
          <td><a href="">{{j.username}}</a></td> 
          
          <td><img src="{{j.Image.url}}" alt="" width="60"></td>
          
          

          <td>
            <div class="btn-group">
                {% if j.Techer == False %}
              <a href="{% url 'accounts:access_users' j.id %}" type="button" class="btn btn-info">Active</a>
              {% else %}
              <a href="{% url 'accounts:access_users_false' j.id %}" type="button" class="btn btn-danger">Unavtive</a>

              {% endif %}
            </div>
          </td>
          
        
        </tr>
        
        {% endfor %}
        <input type="submit">
      
        </tbody>
        <tfoot>
        <tr style="background: black;color: white;">
            <th>Date</th>
            <th>User</th>
            <th>Image</th>
            
            <th>Check</th>
            
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
  {% csrf_token %}
</form>
{% endblock %}

{% block script %}

<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->

<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock %}

accounts/templates/dashboard/List_catagorey.html
{% extends 'base_accounts.html' %}
{% load static %}
{% block List %}active{% endblock %}
{% block list_catagorey %}active{% endblock %}
{% block list_open %}menu-open{% endblock %}


{% block main %}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped" style="text-align: center;">
        <thead>
        <tr>
          <th>date</th>
          <th>Name</th>
          <th>Image</th>
          <th>Update</th>
          
        </tr>
        </thead>
        <tbody>
        {% for j in catagorey %}
        <tr>
          <td>{{j.date}}</td>
          <td>{{j.name}}</td> 
          <td><img src="{{j.image.url}}" alt="" width="60"></td>
          <td>
            <div class="btn-group btn-group-sm">
              <a href="{% url 'accounts:update_catagorey' j.id %}" class="btn btn-info"><i class="fas fa-eye"></i></a>
              <a href="{% url 'accounts:delete_catagorey' j.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
            </div>

          </td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
          <th>Rendering engine</th>
          <th>Browser</th>
          <th>Platform(s)</th>
          <th>Engine version</th>
          
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

{% endblock %}

{% block script %}

<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->

<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock %}

accounts/templates/dashboard/check_comments.html
{% extends 'base_accounts.html' %}
{% load static %}



{% block main %}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped" style="text-align: center;">
        <thead>
        <tr>
          <th>date</th>
          <th>Name</th>
          <th>Catagorey</th>
          <th>Image</th>
          <th>Update</th>
          
        </tr>
        </thead>
        <tbody>
        {% for j in course %}
        <tr>
          <td>{{j.date}}</td>
          <td>{{j.title}}</td> 
          
          <td>
            {% for i in comment %}
            {% if j.id == i.Course.id %}
            <span>{{i}},</span>
            
            {% endif %}
            {% endfor %}
        </td>
        
          
          <td><img src="{{j.image.url}}" alt="" width="60"></td>
          <td>
            <div class="btn-group btn-group-sm">
                <a href="{% url 'accounts:update_course' j.id %}" class="btn btn-info"><i class="fas fa-eye"></i></a>
                <a href="{% url 'accounts:delete_course' j.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
              </div>

          </td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
          <th>Rendering engine</th>
          <th>Browser</th>
          <th>Platform(s)</th>
          <th>Engine version</th>
          
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

{% endblock %}

{% block script %}

<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->

<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock %}

accounts/templates/dashboard/contact_list.html
{% extends 'base_accounts.html' %}
{% load static %}
{% block contact %}active{% endblock %}




{% block main %}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped" style="text-align: center;">
        <thead>
        <tr>
          <th>date</th>
          <th>Name</th>
          <th>Email</th>
          <th>Subjects</th>
          <th>Message</th>
          <th>Auth</th>
        </tr>
        </thead>
        <tbody>
        {% for j in contact %}
        <tr>
          <td>{{j.date}}</td>
          <td>{{j.Name}}</td> 
          <td>{{j.Email}}</td>
          <td>{{j.Sunjects}}</td>
          <td>{{j.Message}}</td>
          <td>
            <div class="btn-group btn-group-sm">
              <a href="{% url 'accounts:update_contact' j.id %}" class="btn btn-info"><i class="fas fa-eye"></i></a>
              <a href="{% url 'accounts:delete_contact' j.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
            </div>

          </td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
          <th>Date</th>
          <th>Name</th>
          <th>Email(s)</th>
          <th>Subjects</th>
          <th>Message</th>
          <th>Auth</th>
          
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

{% endblock %}

{% block script %}

<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->

<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock %}