App/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
    path('accounts/',include('accounts.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import Dashboard,Delete_course,Update_Course,Create_Course,Add_Catagorey,List_Catagorey,Delete_catagorey,Update_Catagorey,Update_User,Register,Login,List_contact,Update_contact,delete_contact,List_user,Parvelege,detail_customer,True_customer,False_customer,Logout_user,Par_Create_User,Accessorey,access_user,access_user_False,List_Course,Update_Customer,Update_Website_specifications,Check_Comments

app_name = 'accounts'

urlpatterns = [
    path('Dashboard/',Dashboard,name='dashboard'),
    path('delete_course/<int:id>/',Delete_course,name='delete_course'),
    path('Update_Course/<int:pk>/',Update_Course.as_view(),name='update_course'),
    path('Create_Course/',Create_Course.as_view(),name='create_course'),
    path('Add_catagorey/',Add_Catagorey.as_view(),name='add_catagorey'),
    path('List_catagorey/',List_Catagorey,name='list_catagorey'),
    path('delete_catagorey/<int:id>/',Delete_catagorey,name='delete_catagorey'),
    path('Update_catagorey/<int:pk>/',Update_Catagorey.as_view(),name='update_catagorey'),
    path('Update_user/<int:pk>/',Update_User.as_view(),name='update_user'),
    path('login/',Login,name='login'),
    path('register/',Register,name='register'),
    path('contact_list/',List_contact,name='list_contact'),
    path('update_contact/<int:pk>/',Update_contact.as_view(),name='update_contact'),
    path('delete/<int:id>/',delete_contact,name='delete_contact'),
    path('list_user/',List_user,name='list_user'),
    path('parvalege/<int:id>/',Parvelege,name='parvalege'),
    path('detail_customer_p/<int:id>/',detail_customer,name='detail_customer_p'),
    path('True_Customer/<int:id>/',True_customer,name='true_customer'),
    path('False_Customer/<int:id>/',False_customer,name='false_customer'),
    path('logout_user',Logout_user,name='logout'),
    path('Par_Create_User/',Par_Create_User,name='Par_Create_User'),
    path('Accessorey/',Accessorey,name='access'),
    path('access_users/<int:id>/',access_user,name='access_users'),
    path('access_users_False/<int:id>/',access_user_False,name='access_users_false'),
    path('list_course/',List_Course,name='list_course'),
    path('Update_Customer/<int:pk>/',Update_Customer.as_view(),name='update_customer'),
    path('Update_About_Web/<int:pk>/',Update_Website_specifications.as_view(),name='update_about_web'),
    path('check_comments/',Check_Comments,name='check_comments'),
]

web/urls.py
from django.urls import path
from .views import Home,Courses,Website,detail_Course,detail_Catagorey,course,customer,contact,Search_Course,delete_Comments,About_us


app_name = 'web'

urlpatterns = [
    
    path('Courses/',Courses,name='courses'),
    path('',Website,name='website'),
    path('detail_Catagorey/<int:id>/',detail_Catagorey,name='detail_Catagorey'),
    path('detail_course/<int:id>/',detail_Course,name='detail_course'),
    path('course/',course,name='course'),
    path('customer/',customer,name='customer'),
    path('contact/',contact.as_view(),name='contact'),
    path('search_course/',Search_Course,name='search_course'),
    path('delete_comment/<int:id>/',delete_Comments,name='delete_comment'),
    path('About_Use/',About_us,name='about_us')
]

web/templates/website/base.html
{% load base_tags %}
{% load static %}
{% load base_tags %}
{% get_about_model as about %}
{% get_customer_count_model as custom %}
{% footer as footer %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>WebUni - Education Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->   
	<link href="{% static 'website/website/img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'website/website/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'website/website/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'website/website/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'website/website/css/style.css' %}"/>
	{% block style %}
	
	<style>
		.site-btn {
			min-width: 92px;
			font-size: 15px;
			font-weight: 500;
		}
		.form-control {
			width: 33%;
			height: calc(3.25rem + 2px);
		}
		.intro-newslatter .site-btn {
			margin: 2% 0;
		}
	</style>
	
	{% endblock %}

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3">
					<div class="site-logo">
						{% if about.logo %}
						<img src="{{about.logo.url}}" alt="">
						{% else %}
						<img src="{% static 'website/website/img/logo.png' %}" alt="">
						{% endif %}
					</div>
					<div class="nav-switch">
						<i class="fa fa-bars"></i>
					</div>
				</div>
				<div class="col-lg-9 col-md-9">
					{% if user.is_authenticated %}
					<a href="{% url 'accounts:dashboard' %}" class="site-btn header-btn" style="display: block; background: transparent;width: 30px;height: 30px;border-radius: 50%;"><img src="{{user.Image.url}}" alt="" style="width: 60%;border-radius: 50%;"></a>
					
					{% else %}
					<a href="{% url 'accounts:login' %}" class="site-btn header-btn" style="background: rgb(33, 146, 161);">Login</a>
					<a href="{% url 'accounts:register' %}" class="site-btn header-btn">Sign Up</a>
					{% endif %}
					<nav class="main-menu">
						<ul>
							<li><a href="{% url 'web:website' %}">Home</a></li>
							<li><a href="{% url 'web:about_us' %}">About us</a></li>
							<li><a href="{% url 'web:course' %}">Courses</a></li>
							
							<li><a href="{% url 'web:contact' %}">Contact</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- Header section end -->

{% block background %}{% endblock %}
	{% block main %}{% endblock %}

<h1>


	
    

	
</h1>
	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Contact Info</h4>
						<ul class="contact-list">
							
							<li>{{about.address}}</li>
							<li>{{about.phone}}</li>
							<li>{{about.email}}</li>
						</ul>
					</div>
					
					<div class="widget-item">
						<h4>Catagorese</h4>

						<ul>
							{% for j in footer %}
							<li><a href="{% url 'web:detail_Catagorey' j.id %}">{{j.name}}</a></li>
							
							{% endfor %}
						</ul>
					</div>
					<div class="widget-item">
						<h4>Website Link</h4>
						<ul>
							<li><a href="{% url 'web:website' %}">Home</a></li>
							<li><a href="{% url 'web:course' %}">Course</a></li>
							<li><a href="">About</a></li>
							<li><a href="{% url 'web:contact' %}">Contact</a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4>Development</h4>
						<ul>
							<li><a href="">Applied Studies</a></li>
							<li><a href="">Computer Engeneering</a></li>
							<li><a href="">Software Engeneering</a></li>
							<li><a href="">Informational Engeneering</a></li>
							<li><a href="">System Engeneering</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Newsletter</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">Subscribe</button>
							<p>*We don’t spam</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Register</a></li>
					<li><a href="#">Privacy</a></li>
				</ul>
				<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
			</div>
		</div>
	</footer> 
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'website/website/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'website/website/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'website/website/js/mixitup.min.js' %}"></script>
	<script src="{% static 'website/website/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'website/website/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'website/website/js/main.js' %}"></script>
	{% block script %}{% endblock %}
</html>